// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/rs/zerolog"
	"gorm.io/gorm"
	config2 "local/art-web/api/internal/infrastructure/config"
	"local/art-web/api/internal/infrastructure/database"
	"local/art-web/api/internal/infrastructure/logger"
)

// Injectors from wire.go:

// InitializeApp returns the assembled *App + cleanup func. Wire generates the
// body in wire_gen.go.
func InitializeApp(ctx context.Context) (*App, func(), error) {
	appConfig, err := config2.Load()
	if err != nil {
		return nil, nil, err
	}
	databaseConfig := appConfig.Database
	db, cleanup, err := database.NewGormDB(databaseConfig)
	if err != nil {
		return nil, nil, err
	}
	loggerConfig := appConfig.Logger
	zerologLogger := logger.New(loggerConfig)
	app := &App{
		DB:     db,
		Logger: zerologLogger,
	}
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// App is the root composition. Cleanup function shuts down server, then DB.
// NOTE: Server *http.Server is omitted here; it has no provider yet and will
// be added in Task 7 when server.ProviderSet lands.
type App struct {
	DB     *gorm.DB
	Logger zerolog.Logger
}
