// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/rs/zerolog"
	"gorm.io/gorm"
	config2 "local/art-web/api/internal/infrastructure/config"
	"local/art-web/api/internal/infrastructure/database"
	"local/art-web/api/internal/infrastructure/logger"
)

// Injectors from wire.go:

// InitializeApp returns the assembled *App + cleanup func. Wire generates the
// body in wire_gen.go.
func InitializeApp(ctx context.Context) (*App, func(), error) {
	appConfig, err := config2.Load()
	if err != nil {
		return nil, nil, err
	}
	databaseConfig := appConfig.Database
	db, cleanup, err := database.NewGormDB(databaseConfig)
	if err != nil {
		return nil, nil, err
	}
	loggerConfig := appConfig.Logger
	zerologLogger := logger.New(loggerConfig)
	app := &App{
		DB:     db,
		Logger: zerologLogger,
	}
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// App is the root composition wired by Wire — currently config + logger + DB
// only. The four slice ProviderSets (auth, user, artwork, image) plus
// server/storage are assembled by hand in main.go below.
//
// SCOPE NOTE (Phase 1 Task 11 carry-over): full slice integration here
// requires typed-string providers for JWT_SIGNING_KEY, WORKER_SIGNING_KEY,
// CookieDomain, AllowedOrigin, FrontendURL, R2Bucket, GoogleClientID/Secret/
// RedirectURL — i.e. a Wire-shaped re-encoding of the cmd/api/config.go
// flattening that main() already does. The decision for Phase 1: keep the
// manual wiring in main() and let Wire own only the cross-cutting infra
// providers, because (a) the manual wiring is one linear pass that's easy
// to read and step through, and (b) adding typed-string providers for every
// env var doubles the surface area without changing runtime behaviour. A
// future phase that introduces a proper config-as-struct provider can move
// to full Wire composition without touching the slices themselves.
type App struct {
	DB     *gorm.DB
	Logger zerolog.Logger
}
