#!/usr/bin/env bash
# dev-up.sh — bring the art-web e2e stack up, seed it, flush web cache.
#
# Usage:
#   ./dev-up.sh                  # wipe data, full rebuild, seed 50
#   ./dev-up.sh --many=120       # seed 120 instead
#   ./dev-up.sh --keep-data      # iterate without losing the bucket / DB
#   ./dev-up.sh --no-flush       # skip web ISR-cache flush (if you don't need it)
#   ./dev-up.sh --no-build       # reuse images (faster when only seeding changed)
#   ./dev-up.sh --init-env       # manage web/.env.local only, then exit

set -euo pipefail

# ── Args ─────────────────────────────────────────────────────────────────────
SEED_COUNT=50
KEEP_DATA=false
NO_FLUSH=false
NO_BUILD=false
INIT_ENV_ONLY=false

for arg in "$@"; do
  case "$arg" in
    --many=*)     SEED_COUNT="${arg#*=}" ;;
    --keep-data)  KEEP_DATA=true ;;
    --no-flush)   NO_FLUSH=true ;;
    --no-build)   NO_BUILD=true ;;
    --init-env)   INIT_ENV_ONLY=true ;;
    -h|--help)
      sed -n '2,10p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "unknown arg: $arg" >&2
      exit 64
      ;;
  esac
done

# ── Paths ────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="$SCRIPT_DIR/web/docker-compose.e2e.yml"
LOCAL_ENV_FILE="$SCRIPT_DIR/web/.env.local"
COMPOSE=(docker compose -f "$COMPOSE_FILE")

# ── Pretty logging ───────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
  C_DIM=$'\e[2m'; C_BOLD=$'\e[1m'; C_OK=$'\e[32m'; C_ERR=$'\e[31m'; C_RESET=$'\e[0m'
else
  C_DIM=""; C_BOLD=""; C_OK=""; C_ERR=""; C_RESET=""
fi
step()  { printf "${C_BOLD}▸ %s${C_RESET}\n" "$*"; }
ok()    { printf "${C_OK}✓ %s${C_RESET}\n" "$*"; }
fail()  { printf "${C_ERR}✗ %s${C_RESET}\n" "$*" >&2; exit 1; }

random_hex_key() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
    return
  fi
  if command -v python3 >/dev/null 2>&1; then
    python3 - <<'PY'
import secrets
print(secrets.token_hex(32))
PY
    return
  fi
  fail "need openssl or python3 to generate local signing keys"
}

write_local_env() {
  local tmp jwt_key worker_key
  tmp="${LOCAL_ENV_FILE}.tmp"
  jwt_key="$(random_hex_key)"
  worker_key="$(random_hex_key)"

  umask 077
  if [[ -f "$LOCAL_ENV_FILE" ]]; then
    awk -v jwt_key="$jwt_key" -v worker_key="$worker_key" '
      BEGIN { saw_jwt = 0; saw_worker = 0 }
      /^JWT_SIGNING_KEY=/ {
        print "JWT_SIGNING_KEY=" jwt_key
        saw_jwt = 1
        next
      }
      /^WORKER_SIGNING_KEY=/ {
        print "WORKER_SIGNING_KEY=" worker_key
        saw_worker = 1
        next
      }
      { print }
      END {
        if (!saw_jwt || !saw_worker) {
          print ""
          print "# Generated by ./dev-up.sh. Do not commit."
          print "# Rotated on destructive dev stack init; preserved with --keep-data."
        }
        if (!saw_jwt) print "JWT_SIGNING_KEY=" jwt_key
        if (!saw_worker) print "WORKER_SIGNING_KEY=" worker_key
      }
    ' "$LOCAL_ENV_FILE" > "$tmp"
  else
    {
      echo "# Generated by ./dev-up.sh. Do not commit."
      echo "# Rotated on destructive dev stack init; preserved with --keep-data."
      echo "JWT_SIGNING_KEY=$jwt_key"
      echo "WORKER_SIGNING_KEY=$worker_key"
    } > "$tmp"
  fi
  mv "$tmp" "$LOCAL_ENV_FILE"
  chmod 600 "$LOCAL_ENV_FILE" 2>/dev/null || true
}

local_env_has_signing_keys() {
  [[ -f "$LOCAL_ENV_FILE" ]] \
    && grep -Eq '^JWT_SIGNING_KEY=[0-9a-fA-F]{64}$' "$LOCAL_ENV_FILE" \
    && grep -Eq '^WORKER_SIGNING_KEY=[0-9a-fA-F]{64}$' "$LOCAL_ENV_FILE"
}

ensure_local_env() {
  local mode=${1:-keep}
  if [[ "$mode" == "rotate" ]] || ! local_env_has_signing_keys; then
    step "generating local signing keys"
    write_local_env
    ok "wrote web/.env.local"
  else
    ok "using existing web/.env.local"
  fi
}

# Block until `probe` exits 0, or fail after `timeout` seconds.
wait_for() {
  local label=$1 probe=$2 timeout=${3:-90}
  local i=0
  printf "  waiting for %s" "$label"
  until eval "$probe" >/dev/null 2>&1; do
    if (( i >= timeout )); then
      printf "\n"
      fail "timed out after ${timeout}s waiting for $label"
    fi
    printf "."
    sleep 1
    i=$((i+1))
  done
  printf " ${C_OK}up${C_RESET} (${C_DIM}${i}s${C_RESET})\n"
}

# ── 1. Local env + optional wipe ─────────────────────────────────────────────
if $INIT_ENV_ONLY; then
  if $KEEP_DATA; then
    ensure_local_env keep
  else
    ensure_local_env rotate
  fi
  exit 0
fi

if $KEEP_DATA; then
  ensure_local_env keep
else
  ensure_local_env rotate
fi

if ! $KEEP_DATA; then
  step "wiping previous containers + volumes"
  "${COMPOSE[@]}" down -v --remove-orphans
fi

# ── 2. Build + boot ──────────────────────────────────────────────────────────
build_flag=()
$NO_BUILD || build_flag=(--build)

step "starting stack ${build_flag[*]:-(no rebuild)}"
# bash 3.2 (macOS stock /bin/bash) treats an empty array as unset under `set -u`,
# so guard the expansion when no extra flags are needed.
if (( ${#build_flag[@]} > 0 )); then
  "${COMPOSE[@]}" up "${build_flag[@]}" -d --wait
else
  "${COMPOSE[@]}" up -d --wait
fi

# ── 3. Probe service readiness ───────────────────────────────────────────────
# `--wait` already blocks on healthchecks, but those checks are defined inside
# the compose file and may not match the public endpoints we care about. We
# probe the actually-reachable URLs to be sure.
wait_for "api"      "curl -sf http://localhost:8080/healthz"
wait_for "web"      "curl -sf -o /dev/null http://localhost:3000"
wait_for "worker"   "curl -sf http://localhost:8787/healthz"

# ── 4. Seed ──────────────────────────────────────────────────────────────────
step "seeding $SEED_COUNT artworks"
SEED_RES="$(curl -sfX POST "http://localhost:8080/dev/seed?many=$SEED_COUNT")" \
  || fail "seed POST failed"

# Extract aliceCookie without depending on jq (portable to bare zsh/bash).
ALICE_COOKIE="$(printf '%s' "$SEED_RES" | sed -n 's/.*"aliceCookie":"\([^"]*\)".*/\1/p')"
P_ID="$(printf '%s' "$SEED_RES" | sed -n 's/.*"pId":"\([^"]*\)".*/\1/p')"

# ── 5. Flush web ISR cache ───────────────────────────────────────────────────
if ! $NO_FLUSH; then
  step "flushing web .next/cache + restarting web"
  "${COMPOSE[@]}" exec -T web sh -c 'rm -rf .next/cache' \
    && "${COMPOSE[@]}" restart web >/dev/null
  wait_for "web (post-restart)" "curl -sf -o /dev/null http://localhost:3000"
fi

# ── 6. Summary ───────────────────────────────────────────────────────────────
echo
ok "stack ready"
echo "  http://localhost:3000     web"
echo "  http://localhost:8080     api"
echo "  http://localhost:9001     minio console (minioadmin/minioadmin)"
echo
ok "seeded ${SEED_COUNT} bulk artworks (+ public P, private Q)"
[[ -n "$P_ID" ]] && echo "  public artwork P id: $P_ID"
echo
echo "to sign in as alice, paste this into devtools › application › cookies:"
echo "  ${C_DIM}name:${C_RESET}  auth"
echo "  ${C_DIM}value:${C_RESET} ${ALICE_COOKIE#auth=}"
echo "  ${C_DIM}path:${C_RESET}  /"
